services:
  - type: web
    name: swiss-watches-mauritania
    env: docker
    plan: free # Change to starter or higher for persistence (Disk)
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: swiss-watches-db
          property: connectionString
      - key: INTERNAL_DATABASE_URL
        fromDatabase:
          name: swiss-watches-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 20

databases:
  - name: swiss-watches-db
    plan: free
