services:
  - type: web
    name: swiss-watches-mauritania
    env: docker
    plan: free # Change to starter or higher for persistence (Disk)
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true # Temporairement à true pour le diagnostic
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      # DATABASE_URL est injecté automatiquement par Render si vous liez une DB PostgreSQL
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 20
    # Uncomment below for persistence (requires a paid plan)
    # disks:
    #   - name: sqlite-data
    #     mountPath: /opt/render/project/src/database
    #     sizeGB: 1
